wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      3:
      - 3
      4: 3.7.4
      5: 0.10.30
      8:
      - 5
k:
  desc: null
  value: 4
learningRate:
  desc: null
  value: 5.0e-07
numIterations:
  desc: null
  value: 10000
type:
  desc: null
  value: modified
xDim:
  desc: null
  value:
  - 100000
  - 4
