wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1633334989
    t:
      3:
      - 2
      - 3
      - 16
      - 17
      4: 3.7.4
      5: 0.12.2
      8:
      - 5
flags:
  desc: null
  value:
  - -momentum
isSymmetric:
  desc: null
  value: false
k:
  desc: null
  value: 5
learningRate:
  desc: null
  value: 1.0e-09
numIterations:
  desc: null
  value: 35000
numStepsPerIteration:
  desc: null
  value: 25
tolerance:
  desc: null
  value: 10
variant:
  desc: null
  value: c
xDim:
  desc: null
  value:
  - 10000
  - 5
