wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      3:
      - 3
      4: 3.7.4
      5: 0.10.30
      8:
      - 5
flags:
  desc: null
  value:
  - -playEigenGame
  - -modified
k:
  desc: null
  value: 3
learningRate:
  desc: null
  value: 1
numIterations:
  desc: null
  value: 10000
xDim:
  desc: null
  value:
  - 100000
  - 4
