wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1633440517
    t:
      3:
      - 2
      - 3
      - 16
      - 17
      4: 3.7.4
      5: 0.12.2
      8:
      - 5
distanceTolerance:
  desc: null
  value: 0.01
flags:
  desc: null
  value:
  - -rmsprop
  - -repeatedEVtest
isSymmetric:
  desc: null
  value: false
k:
  desc: null
  value: 3
learningRate:
  desc: null
  value: 0.001
numIterations:
  desc: null
  value: 35000
numStepsPerIteration:
  desc: null
  value: 200
tolerance:
  desc: null
  value: 10
variant:
  desc: null
  value: c
xDim:
  desc: null
  value:
  - 10000
  - 5
